#-*- coding: utf-8 -*-
from odoo import models, fields, api


class AccountMove(models.Model):
    _inherit = 'account.move'

    state = fields.Selection(selection_add=[('fc_control', 'FC Approval'), ('cfo_approve', 'CFO Approval')],
                             ondelete={'fc_control': 'cascade', 'cfo_approve': 'cascade'})


class AccountPayment(models.Model):
    _inherit = 'account.payment'

    approve_uid = fields.Many2one(comodel_name='res.users', string='Approved By', required=False)
    check_uid = fields.Many2one(comodel_name='res.users', string='Checked By', required=False)
    narration = fields.Text(string="Narration", required=False)

    def fc_approve(self):
        user = self.env.user
        user_id = user.id
        self.write({
            'state': 'fc_control',
        })
        self.approve_uid = user_id

    def cfo_approve(self):
        user = self.env.user
        user_id = user.id
        self.write({
            'state': 'cfo_approve',
        })
        self.check_uid = user_id

    def _compute_amount2words(self):
        for rec in self:
                rec.amount_words = str(rec.currency_id.amount_to_text(rec.amount))

    amount_words = fields.Char(string="Total amount in words: ", help=
        "Total amount in words is automatically generated by the system", compute='_compute_amount2words')



# class payment_voucher(models.Model):
#     _name = 'payment_voucher.payment_voucher'
#     _description = 'payment_voucher.payment_voucher'

#     name = fields.Char()
#     value = fields.Integer()
#     value2 = fields.Float(compute="_value_pc", store=True)
#     description = fields.Text()
#
#     @api.depends('value')
#     def _value_pc(self):
#         for record in self:
#             record.value2 = float(record.value) / 100
